### ISSUE TITLE
FTBFS with Vala 0.56.18 (Compact class cannot inherit from non-compact class)

### ISSUE THREAD

**Issue by bobby285271** [elementary/monitor#444]
### What Happened?

:wave: Hi, both 0.17.2 and current master fails to build with vala 0.56.18 for me.

I think this is caused by https://gitlab.gnome.org/GNOME/vala/-/commit/34e2c6c5dcf5e89a7bec017bf440bb5e64aa4a77

Full log: [monitor-build-log.txt](https://github.com/user-attachments/files/20326687/monitor-build-log.txt)

```
../src/Resources/Hwmon/HwmonTemperature.vala:11.1-11.46: error: Compact class `Monitor.HwmonTemperature' cannot inherit from non-compact class `GLib.Object'
   11 | public class Monitor.HwmonTemperature : Object {
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  
../src/Resources/CPUCache.vala:9.1-9.38: error: Compact class `Monitor.CPUCache' cannot inherit from non-compact class `GLib.Object'
    9 | public class Monitor.CPUCache : Object {
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  
../src/Resources/Storage/Volume.vala:7.1-7.36: error: Compact class `Monitor.Volume' cannot inherit from non-compact class `GLib.Object'
    7 | public class Monitor.Volume : Object {
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  
../src/Resources/Hwmon/HwmonVoltage.vala:10.1-10.42: error: Compact class `Monitor.HwmonVoltage' cannot inherit from non-compact class `GLib.Object'
   10 | public class Monitor.HwmonVoltage : Object {
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  
../src/Resources/Hwmon/HwmonFrequency.vala:10.1-10.44: error: Compact class `Monitor.HwmonFrequency' cannot inherit from non-compact class `GLib.Object'
   10 | public class Monitor.HwmonFrequency : Object {
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  
../src/Resources/Hwmon/HwmonFan.vala:10.1-10.38: error: Compact class `Monitor.HwmonFan' cannot inherit from non-compact class `GLib.Object'
   10 | public class Monitor.HwmonFan : Object {
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  
../src/Resources/Hwmon/HwmonPWM.vala:10.1-10.38: error: Compact class `Monitor.HwmonPWM' cannot inherit from non-compact class `GLib.Object'
   10 | public class Monitor.HwmonPWM : Object {
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  
../src/Resources/Hwmon/HwmonPower.vala:10.1-10.40: error: Compact class `Monitor.HwmonPower' cannot inherit from non-compact class `GLib.Object'
   10 | public class Monitor.HwmonPower : Object {
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  
Compilation failed: 8 error(s), 0 warning(s)
```

### Steps to Reproduce

1. Build with Vala 0.56.18

### Expected Behavior

Builds.

### OS Version

Other Linux

### Session Type

Classic Session (X11, This is the default)

### Software Version

Compiled from git

### Log Output

```shell

```
